var ovj = {
  "page": 1,
  "results": [
    {
      "adult": false,
      "backdrop_path": "/bckxSN9ueOgm0gJpVJmPQrecWul.jpg",
      "genre_ids": [28, 12, 14],
      "id": 572802,
      "original_language": "en",
      "original_title": "Aquaman and the Lost Kingdom",
      "overview":
        "Black Manta, still driven by the need to avenge his father's death and wielding the power of the mythic Black Trident, will stop at nothing to take Aquaman down once and for all. To defeat him, Aquaman must turn to his imprisoned brother Orm, the former King of Atlantis, to forge an unlikely alliance in order to save the world from irreversible destruction.",
      "popularity": 1928.895,
      "poster_path": "/8xV47NDrjdZDpkVcCFqkdHa3T0C.jpg",
      "release_date": "2023-12-20",
      "title": "Aquaman and the Lost Kingdom",
      "video": false,
      "vote_average": 6.4,
      "vote_count": 119,
    },
    {
      "adult": false,
      "backdrop_path": "/bmlkLCjrIWnnZzdAQ4uNPG9JFdj.jpg",
      "genre_ids": [35, 10751, 14],
      "id": 787699,
      "original_language": "en",
      "original_title": "Wonka",
      "overview":
        "Willy Wonka – chock-full of ideas and determined to change the world one delectable bite at a time – is proof that the best things in life begin with a dream, and if you’re lucky enough to meet Willy Wonka, anything is possible.",
      "popularity": 950.379,
      "poster_path": "/qhb1qOilapbapxWQn9jtRCMwXJF.jpg",
      "release_date": "2023-12-06",
      "title": "Wonka",
      "video": false,
      "vote_average": 7.2,
      "vote_count": 477,
    },
    {
      "adult": false,
      "backdrop_path": "/k1KrbaCMACQiq7EA0Yhw3bdzMv7.jpg",
      "genre_ids": [16, 10751, 10402, 14, 35],
      "id": 901362,
      "original_language": "en",
      "original_title": "Trolls Band Together",
      "overview":
        "When Branch's brother, Floyd, is kidnapped for his musical talents by a pair of nefarious pop-star villains, Branch and Poppy embark on a harrowing and emotional journey to reunite the other brothers and rescue Floyd from a fate even worse than pop-culture obscurity.",
      "popularity": 608.676,
      "poster_path": "/bkpPTZUdq31UGDovmszsg2CchiI.jpg",
      "release_date": "2023-10-12",
      "title": "Trolls Band Together",
      "video": false,
      "vote_average": 7.2,
      "vote_count": 404,
    },
    {
      "adult": false,
      "backdrop_path": "/4uHyfIApZSRXSVEqSuk92PdN8Yx.jpg",
      "genre_ids": [10751, 35, 14],
      "id": 8871,
      "original_language": "en",
      "original_title": "How the Grinch Stole Christmas",
      "overview":
        "The Grinch decides to rob Whoville of Christmas - but a dash of kindness from little Cindy Lou Who and her family may be enough to melt his heart...",
      "popularity": 471.337,
      "poster_path": "/52EpMoLTTbKAkM6rSrnNHV2mpLF.jpg",
      "release_date": "2000-11-17",
      "title": "How the Grinch Stole Christmas",
      "video": false,
      "vote_average": 6.8,
      "vote_count": 6917,
    },
    {
      "adult": false,
      "backdrop_path": "/5lWIYxYEqWi8j3ZloxXntw3ImBo.jpg",
      "genre_ids": [16, 10751, 35, 14],
      "id": 360920,
      "original_language": "en",
      "original_title": "The Grinch",
      "overview":
        "The Grinch hatches a scheme to ruin Christmas when the residents of Whoville plan their annual holiday celebration.",
      "popularity": 457.68,
      "poster_path": "/1Bc9VNd9CIHIyJtPKFqSQzrXWru.jpg",
      "release_date": "2018-11-08",
      "title": "The Grinch",
      "video": false,
      "vote_average": 6.8,
      "vote_count": 3568,
    },
    {
      "adult": false,
      "backdrop_path": "/nHf61UzkfFno5X1ofIhugCPus2R.jpg",
      "genre_ids": [35, 12, 14],
      "id": 346698,
      "original_language": "en",
      "original_title": "Barbie",
      "overview":
        "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.",
      "popularity": 410.633,
      "poster_path": "/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
      "release_date": "2023-07-19",
      "title": "Barbie",
      "video": false,
      "vote_average": 7.2,
      "vote_count": 6414,
    },
    {
      "adult": false,
      "backdrop_path": "/9QusGjxcYvfPD1THg6oW3RLeNn7.jpg",
      "genre_ids": [28, 12, 14],
      "id": 297802,
      "original_language": "en",
      "original_title": "Aquaman",
      "overview":
        "Once home to the most advanced civilization on Earth, Atlantis is now an underwater kingdom ruled by the power-hungry King Orm. With a vast army at his disposal, Orm plans to conquer the remaining oceanic people and then the surface world. Standing in his way is Arthur Curry, Orm's half-human, half-Atlantean brother and true heir to the throne.",
      "popularity": 388.918,
      "poster_path": "/xLPffWMhMj1l50ND3KchMjYoKmE.jpg",
      "release_date": "2018-12-07",
      "title": "Aquaman",
      "video": false,
      "vote_average": 6.9,
      "vote_count": 13168,
    },
    {
      "adult": false,
      "backdrop_path": "/9n2tJBplPbgR2ca05hS5CKXwP2c.jpg",
      "genre_ids": [16, 10751, 12, 14, 35],
      "id": 502356,
      "original_language": "en",
      "original_title": "The Super Mario Bros. Movie",
      "overview":
        "While working underground to fix a water main, Brooklyn plumbers—and brothers—Mario and Luigi are transported down a mysterious pipe and wander into a magical new world. But when the brothers are separated, Mario embarks on an epic quest to find Luigi.",
      "popularity": 377.186,
      "poster_path": "/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg",
      "release_date": "2023-04-05",
      "title": "The Super Mario Bros. Movie",
      "video": false,
      "vote_average": 7.7,
      "vote_count": 7497,
    },
    {
      "adult": false,
      "backdrop_path": "/h3X1YZXNeklLNKRVOS6DHGRosog.jpg",
      "genre_ids": [27, 35, 14],
      "id": 287903,
      "original_language": "en",
      "original_title": "Krampus",
      "overview":
        "When his dysfunctional family clashes over the holidays, young Max is disillusioned and turns his back on Christmas.  Little does he know, this lack of festive spirit has unleashed the wrath of Krampus: a demonic force of ancient evil intent on punishing non-believers.",
      "popularity": 317.845,
      "poster_path": "/sAolMRD9rFSTU7tssfFuLEJJa7w.jpg",
      "release_date": "2015-11-26",
      "title": "Krampus",
      "video": false,
      "vote_average": 6.2,
      "vote_count": 2002,
    },
    {
      "adult": false,
      "backdrop_path": "/jhpsTzbXEu5bkCPmBqxv7vUTjIT.jpg",
      "genre_ids": [14, 12, 878, 28],
      "id": 566810,
      "original_language": "en",
      "original_title": "Dragon Kingdom",
      "overview":
        "To save their Kingdom from an army of undead, a group of warriors must travel through the forbidden lands fighting the fearsome beasts that call The Dark Kingdom their home.",
      "popularity": 317.196,
      "poster_path": "/o7StI2iR8yY1N67meSkNcXfojyD.jpg",
      "release_date": "2018-11-26",
      "title": "The Dark Kingdom",
      "video": false,
      "vote_average": 5.7,
      "vote_count": 41,
    },
    {
      "adult": false,
      "backdrop_path": "/4fLZUr1e65hKPPVw0R3PmKFKxj1.jpg",
      "genre_ids": [16, 35, 10751, 14, 10749],
      "id": 976573,
      "original_language": "en",
      "original_title": "Elemental",
      "overview":
        "In a city where fire, water, land and air residents live together, a fiery young woman and a go-with-the-flow guy will discover something elemental: how much they have in common.",
      "popularity": 303.966,
      "poster_path": "/4Y1WNkd88JXmGfhtWR7dmDAo1T2.jpg",
      "release_date": "2023-06-14",
      "title": "Elemental",
      "video": false,
      "vote_average": 7.7,
      "vote_count": 3259,
    },
    {
      "adult": false,
      "backdrop_path": "/4MUfDtBqUFqotGF5RJOfNfoBTLo.jpg",
      "genre_ids": [28, 27, 14],
      "id": 951546,
      "original_language": "en",
      "original_title": "Reign of Chaos",
      "overview":
        "When the world is gripped by a plague unleashed by the evil lord Chaos, and humans are turned into rabid creatures, mankind can only be saved by three young women, descendants of a Goddess, with the power to stop Chaos' evil.",
      "popularity": 279.48,
      "poster_path": "/nTMmpvR9TyV631tpFr4FtYxG0FC.jpg",
      "release_date": "2022-04-12",
      "title": "Reign of Chaos",
      "video": false,
      "vote_average": 5.8,
      "vote_count": 29,
    },
    {
      "adult": false,
      "backdrop_path": "/ehumsuIBbgAe1hg343oszCLrAfI.jpg",
      "genre_ids": [16, 10751, 14, 12],
      "id": 1022796,
      "original_language": "en",
      "original_title": "Wish",
      "overview":
        "Asha, a sharp-witted idealist, makes a wish so powerful that it is answered by a cosmic force – a little ball of boundless energy called Star. Together, Asha and Star confront a most formidable foe - the ruler of Rosas, King Magnifico - to save her community and prove that when the will of one courageous human connects with the magic of the stars, wondrous things can happen.",
      "popularity": 270.341,
      "poster_path": "/AcoVfiv1rrWOmAdpnAMnM56ki19.jpg",
      "release_date": "2023-11-13",
      "title": "Wish",
      "video": false,
      "vote_average": 6.6,
      "vote_count": 145,
    },
    {
      "adult": false,
      "backdrop_path": "/sERD1155J1cJyXug1QwlA0fa354.jpg",
      "genre_ids": [14],
      "id": 995906,
      "original_language": "en",
      "original_title": "Galaxy Games",
      "overview":
        "A group of young adults are sent to a faraway planet to compete in the prestigious Sol Invictus games. When disaster strikes and the teams are stranded without equipment or communication, they must work together to survive long enough to be rescued.",
      "popularity": 242.594,
      "poster_path": "/8aoIMYZUu8DRrJFkDvz13rehSFL.jpg",
      "release_date": "2022-07-04",
      "title": "Galaxy Games",
      "video": false,
      "vote_average": 5.7,
      "vote_count": 7,
    },
    {
      "adult": false,
      "backdrop_path": "/faXT8V80JRhnArTAeYXz0Eutpv9.jpg",
      "genre_ids": [12, 14, 16, 35, 10751, 28],
      "id": 315162,
      "original_language": "en",
      "original_title": "Puss in Boots: The Last Wish",
      "overview":
        "Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.",
      "popularity": 212.144,
      "poster_path": "/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
      "release_date": "2022-12-07",
      "title": "Puss in Boots: The Last Wish",
      "video": false,
      "vote_average": 8.3,
      "vote_count": 6743,
    },
    {
      "adult": false,
      "backdrop_path": "/bSvUW4JQ6g4QiKvwejcfcPRd4Ke.jpg",
      "genre_ids": [12, 35, 10751, 14],
      "id": 118,
      "original_language": "en",
      "original_title": "Charlie and the Chocolate Factory",
      "overview":
        "A young boy wins a tour through the most magnificent chocolate factory in the world, led by the world's most unusual candy maker.",
      "popularity": 202.153,
      "poster_path": "/wfGfxtBkhBzQfOZw4S8IQZgrH0a.jpg",
      "release_date": "2005-07-13",
      "title": "Charlie and the Chocolate Factory",
      "video": false,
      "vote_average": 7,
      "vote_count": 14224,
    },
    {
      "adult": false,
      "backdrop_path": "/sp6egj5NHHRGmCMdIoTNdbLwACR.jpg",
      "genre_ids": [35, 14, 10751],
      "id": 1022964,
      "original_language": "en",
      "original_title": "Candy Cane Lane",
      "overview":
        "A man, determined to win the neighborhood's annual Christmas decorating contest, makes a pact with an elf to help him win. However, the elf casts a spell bringing the twelve days of Christmas to life, bringing chaos to the small, unsuspecting town.",
      "popularity": 201.969,
      "poster_path": "/of6Ds591FJTKoBHYjDFzH6jlTyK.jpg",
      "release_date": "2023-11-29",
      "title": "Candy Cane Lane",
      "video": false,
      "vote_average": 6.2,
      "vote_count": 222,
    },
    {
      "adult": false,
      "backdrop_path": "/1HHp75V06ymY19lRqU7EPRv55Jt.jpg",
      "genre_ids": [12, 16, 14],
      "id": 872976,
      "original_language": "ja",
      "original_title": "デジモンアドベンチャー02 THE BEGINNING",
      "overview":
        "In 2012, after the events of Digimon Adventure: Last Evolution Kizuna, the early adulthood DigiDestined—Daisuke, Miyako, Iori, Takeru Takashi, Hikari, and Ken—must reconcile their new responsibilities with their Digimon partners. But Rui Owada, a mysterious young man,  appears, claiming to be the first human to partner with a Digimon–Ukkomon. Could Rui really have been the first-ever DigiDestined?",
      "popularity": 186.491,
      "poster_path": "/rYblAHp4k7xK6MDRcGM3GDB6QdV.jpg",
      "release_date": "2023-10-27",
      "title": "Digimon Adventure 02: The Beginning",
      "video": false,
      "vote_average": 6.8,
      "vote_count": 5,
    },
    {
      "adult": false,
      "backdrop_path": "/idfNNlVwjVkBQrM2eWpLZiDOTIc.jpg",
      "genre_ids": [10751, 14, 35],
      "id": 252,
      "original_language": "en",
      "original_title": "Willy Wonka & the Chocolate Factory",
      "overview":
        "When eccentric candy man Willy Wonka promises a lifetime supply of sweets and a tour of his chocolate factory to five lucky kids, penniless Charlie Bucket seeks the golden ticket that will make him a winner.",
      "popularity": 186.245,
      "poster_path": "/vmpsZkrs4Uvkp9r1atL8B3frA63.jpg",
      "release_date": "1971-06-29",
      "title": "Willy Wonka & the Chocolate Factory",
      "video": false,
      "vote_average": 7.5,
      "vote_count": 3203,
    },
    {
      "adult": false,
      "backdrop_path": "/hziiv14OpD73u9gAak4XDDfBKa2.jpg",
      "genre_ids": [12, 14],
      "id": 671,
      "original_language": "en",
      "original_title": "Harry Potter and the Philosopher's Stone",
      "overview":
        "Harry Potter has lived under the stairs at his aunt and uncle's house his whole life. But on his 11th birthday, he learns he's a powerful wizard—with a place waiting for him at the Hogwarts School of Witchcraft and Wizardry. As he learns to harness his newfound powers with the help of the school's kindly headmaster, Harry uncovers the truth about his parents' deaths—and about the villain who's to blame.",
      "popularity": 184.193,
      "poster_path": "/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg",
      "release_date": "2001-11-16",
      "title": "Harry Potter and the Philosopher's Stone",
      "video": false,
      "vote_average": 7.9,
      "vote_count": 25798,
    },
  ],
  "total_pages": 984,
  "total_results": 19668,
};
